### ISSUE TITLE
Segfault in tab

### ISSUE THREAD

**Issue by rendom** [fulhax/ncpamixer#8] opened 2016-08-20 17:35 UTC
```
Thread 1 "ncpamixer" received signal SIGSEGV, Segmentation fault.
0x0000000000433228 in Tab::draw (this=0x6f2d00)
    at /ff/github/pulsemixer/src/ui/tab.cpp:93
93                char *name = toggle->find(i.second->getRelation())->second->name;
(gdb) bt
#0  0x0000000000433228 in Tab::draw (this=0x6f2d00) at /ff/gitstuff/github/pulsemixer/src/ui/tab.cpp:93
#1  0x000000000043299f in Ui::draw (this=0x645c60 <ui>) at /ff/github/pulsemixer/src/ui/ui.cpp:304
#2  0x00000000004329ee in Ui::run (this=0x645c60 <ui>) at /ff/github/pulsemixer/src/ui/ui.cpp:314
#3  0x0000000000426c25 in main (argc=1, argv=0x7fffffffe008) at /ff/github/pulsemixer/src/pulsemixer.cpp:79
(gdb)
```

**Comment by c0r73x** [comment] 2016-08-22 08:07
I cant reproduce it, but I guess that the problem is that it enters a codepath in a tab that don't have toggle.

**Comment by c0r73x** [comment] 2017-09-21 08:34
Fixed in dev.

**Closed by c0r73x** 2017-09-21 08:34 UTC
Labels: bug
